#!/bin/bash

# Actualización del Sistema
echo "[TASK 1] Actualización del Sistema"
#yum update -y >/dev/null 2>&1

# Instalación de Paquetes
echo "[TASK 2] Instalación de Paquetes"
#yum install -y -q vim redhat-lsb-core net-tools bind-utils >/dev/null 2>&1
#yum install -y wget

# Configuración de Alias
echo "[TASK 3] Configuración de Alias"
#cat >>/etc/bashrc <<EOF
# Generated by Vagrant
#alias vi='vim'
#alias sudo='sudo '
#export EDITOR=vim
#export TERM=xterm
# Generated by Vagrant
#EOF

echo "colorscheme elflord" >> /etc/vimrc

# Habilitación de autenticación mediante contraseña
echo "[TASK 4] Enabling password authentication in sshd config"
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

# Deshabilitar SELinux
echo "[TASK 5] Disable SELinux"
setenforce 0
sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

# Setear Password de Root
echo "[TASK 6] Set root password"
echo "admin" | passwd --stdin root >/dev/null 2>&1

# Deshabilitar y detener Firewall
echo "[TASK 5] Disable and stop firewalld"
systemctl disable firewalld >/dev/null 2>&1
systemctl stop firewalld

# Actualizar archivo hosts
echo "[TASK 6] Update /etc/hosts file"
cat >>/etc/hosts<<EOF
172.42.42.10 server01.example.com server01
172.42.42.20 server02.example.com server02
172.42.42.30 server03.example.com server03
172.42.42.40 server04.example.com server04
EOF
